version: '3.8'

services:
  lps-brands:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
        - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
        - NEXT_PUBLIC_SANITY_API_VERSION=${NEXT_PUBLIC_SANITY_API_VERSION}
        - NEXT_PUBLIC_SANITY_API_TOKEN=${NEXT_PUBLIC_SANITY_API_TOKEN}
    container_name: lps-brands
    restart: unless-stopped
    ports:
      - "3020:3000"
    environment:
      - NODE_ENV=production
    networks:
      - lps-network

networks:
  lps-network:
    driver: bridge
